// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/articles/getone/[id].ts";
import * as $3 from "./routes/api/articles/list.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/users/register.ts";
import * as $6 from "./routes/details/[id].tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/my/add.tsx";
import * as $9 from "./routes/search.tsx";
import * as $10 from "./routes/user/login.tsx";
import * as $11 from "./routes/user/register.tsx";
import * as $$0 from "./islands/AddForm.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/Navbar.tsx";
import * as $$3 from "./islands/loginForm.tsx";
import * as $$4 from "./islands/pagination.tsx";
import * as $$5 from "./islands/regiterForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/articles/getone/[id].ts": $2,
    "./routes/api/articles/list.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/users/register.ts": $5,
    "./routes/details/[id].tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/my/add.tsx": $8,
    "./routes/search.tsx": $9,
    "./routes/user/login.tsx": $10,
    "./routes/user/register.tsx": $11,
  },
  islands: {
    "./islands/AddForm.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/Navbar.tsx": $$2,
    "./islands/loginForm.tsx": $$3,
    "./islands/pagination.tsx": $$4,
    "./islands/regiterForm.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
